### ISSUE TITLE
ARM64 Images are Actually AMD64

### ISSUE THREAD

**Issue by joshkraan** [Michsior14/docker-mods#6]
First of all, thank you for creating this!

I haven't been able to get this working on my ARM64 system, as the transmission-gluetun-port-update binary is compiled for AMD64 in all of the ARM64 images that I tested. I tried building the image locally, and the binary is properly compiled for ARM64; this would point to an issue in the Github Actions cross-compilation workflow, but I haven't been able to find anything that looks incorrect. Are there any references to the local platform hidden anywhere?

Unfortunately, local images can't be used as Linuxserver docker mods, so it would be great if this issue could be fixed. I am happy to test changes.

**Comment by Michsior14** [comment]
Hey, I will check the pipelines after Christmas time or in the beginning of the next year. In the meantime if you find something keep me posted;)

**Comment by joshkraan** [comment]
After some further testing, I believe that this can be closed as the images are actually being built correctly. 

What led me to believe that the images were being built incorrectly was that the transmission-gluetun-port-update binary was compiled for AMD64 in the Linuxserver/transmission image. However, if I just pull the image directly, the binary is properly compiled for ARM64. 

So it seems that this issue is coming from how the Linuxserver/transmission docker mods are installed, which I will look into. The other docker mod I have installs correctly, so this could still be a different issue with this docker mod. I will start a new issue if that looks likely.
