### ISSUE TITLE
Docker Mod Multi-Architecture Support 

### ISSUE THREAD

**Issue by joshkraan** [Michsior14/docker-mods#7]
I believe I have figured out why the linuxserver/transmission image pulls the AMD64 version of this docker mod on ARM64 (issue #6). Fixing this issue would require some changes to how this is built, which I am happy to work on (I will fork these repos, and later submit pull requests).

From what I can tell, it seems that by design only the AMD64 version of a mod will be pulled, regardless of the platform. To support multiple platforms, multiple binaries compiled for different architectures should be included in a single docker image, and a bash script should be used to decide which binary to use. [linuxserver/mods:code-server-powershell](https://github.com/linuxserver/docker-mods/tree/code-server-powershell) is a good example of this.

To accomplish this, I think the following would make sense:
1. Build and release the binaries for multiple architectures in [Michsior14/transmission-gluetun-port-update](https://github.com/Michsior14/transmission-gluetun-port-update).
2. In this repo, the Dockerfile would simply download all of the binaries and put them into a single AMD64 docker image. 
3. When this is added as a docker mod, the linuxserver/transmission image will pull that single image, regardless of the platform. A startup script would then detect the user's architecture and which binary to run.

**Comment by Michsior14** [comment]
@joshkraan Please test if the changes fixed issues on arm64.

**Comment by joshkraan** [comment]
Thank you for making these changes so quickly!

I have confirmed that with this fix everything works properly on arm64.
